name: ProSeisSN
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - ipython
  - certifi
  - cartopy
  - obspy
  - numpy
  - scipy
  - matplotlib
  - pathlib
  - pyrocko
  - jupyter
  - jupyterlab
  - utm
  - segyio
  - netcdf4
  - pyrocko::pyrocko
  - collections-extended

  #--- Repos  ---#
  # Check conda packages -> https://conda-forge.org/packages/
  
  #  - numba
  #  - pandas
  #  - pip
  #  - pip:
  #    - libmseed
  #  - seaborn
  #  - xarray
  #  - packaging
  #  - gmt
  #  - pygmt
  #  - mpi4py=3.0.1
  #  - pyasdf
