name: ProSeisSN
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - ipython
  - certifi
  - cartopy
  - libmseed
  - obspy
  - numpy
  - scipy
  - matplotlib
  - numba
  - pathlib
  - pyrocko
  - jupyter
  - jupyterlab
  - utm
  - segyio
  - collections
  - netcdf4

  #--- Repos  ---#
  #  - pandas
  #  - pip
  #  - seaborn
  #  - xarray
  #  - packaging
  #  - gmt
  #  - pygmt
  #  - mpi4py=3.0.1
  #  - pyasdf
