name: ProSeisSN
channels:
  - conda-forge
  - defaults
  - pip
dependencies:
  - python
  - ipython
  - certifi
  - cartopy
  - obspy
  - numpy
  - scipy
  - matplotlib
  - ipympl
  - ipywidgets>=8.1.5
  - widgetsnbextension>=4.0.13
  - pathlib
  - pyrocko
  - jupyter
  - jupyterlab
  - utm
  - segyio
  - netcdf4
  - pyrocko::pyrocko
  - collections-extended
  - pyproj
  - ipython
  - notebook
  - scikit-learn
  - scikit-image
  - pyasdf
  - pytorch
  - nvidia
  - numba
  - pandas
  - pylops>=2.0.0
  
  #--- Repos  ---#
  # Check conda packages -> https://conda-forge.org/packages/
  #  - numba
  #  - pandas
  #  - pip
  #  - pip:
  #    - libmseed
  #  - seaborn
  #  - xarray
  #  - packaging
  #  - gmt
  #  - pygmt
  #  - mpi4py=3.0.1
  #  - pyasdf

